
CREATE TABLE ANSWER
(
  ANSWER       VARCHAR(50)  NOT NULL,
  ANSWER_ID    VARCHAR(50)  NOT NULL,
  QUESTION_ID  VARCHAR(500) NOT NULL,
  USER_NAME_ID VARCHAR(50)  NOT NULL,
  PRIMARY KEY (ANSWER_ID)
) COMMENT '답변';

CREATE TABLE QUESTION
(
  QUESTION    VARCHAR(500) NOT NULL,
  QUESTION_ID VARCHAR(500) NOT NULL,
  PRIMARY KEY (QUESTION_ID)
) COMMENT '문항';

CREATE TABLE STATISTICS
(
  QUESTION_ID   VARCHAR(500) NOT NULL,
  ANSWER_ID     VARCHAR(50)  NOT NULL,
  USER_NAME_ID  VARCHAR(50)  NOT NULL,
  STATISTICS_ID VARCHAR(50)  NOT NULL,
  PRIMARY KEY (STATISTICS_ID)
) COMMENT '통계';

CREATE TABLE USER
(
  USER_NAME    VARCHAR(50) NOT NULL,
  USER_NAME_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY (USER_NAME_ID)
) COMMENT '설문자';

ALTER TABLE ANSWER
  ADD CONSTRAINT FK_QUESTION_TO_ANSWER
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTION (QUESTION_ID);

ALTER TABLE STATISTICS
  ADD CONSTRAINT FK_QUESTION_TO_STATISTICS
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTION (QUESTION_ID);

ALTER TABLE STATISTICS
  ADD CONSTRAINT FK_ANSWER_TO_STATISTICS
    FOREIGN KEY (ANSWER_ID)
    REFERENCES ANSWER (ANSWER_ID);

ALTER TABLE STATISTICS
  ADD CONSTRAINT FK_USER_TO_STATISTICS
    FOREIGN KEY (USER_NAME_ID)
    REFERENCES USER (USER_NAME_ID);

ALTER TABLE ANSWER
  ADD CONSTRAINT FK_USER_TO_ANSWER
    FOREIGN KEY (USER_NAME_ID)
    REFERENCES USER (USER_NAME_ID);
